### PR TITLE
Improved: Remove diode footprint from the top surface

### LINKED ISSUE #8: Remove diode footprint from the top surface
Following up on the comment in PR #5, I think this is better to discuss in an Issue first.

> ...
> Also I agree with moving the diodes now that they will be soldered on the bottom side, but the diodes on the top surface should be removed at the same time.
>
> _Originally posted by @duckyb in https://github.com/duckyb/urchin/issues/5#issuecomment-1973554221_

With removing the Diods on the top side, do you mean something like what was done in #6? (the right through hole could also be removed I think)

If you are interested, I could start fresh from the current main and replace the diods. Result would look something like

### PR DESCRIPTION
**Pull request by ToppDev**
I made 3 improvements to PR #9 / PR #6. Closes #8 

- Move track from logo
- SW17: Move the track to the back to simplify routing and stop using the 2nd via of the diode
- Remove the 2nd via of all diodes because not used

I made some screenshots and gifs of the PCB to make the review easier

# Left

<details>
  <summary>Pictures</summary>

Left-ToppDev
Left-duckyb-feature
Left-duckyb-master

</details>

<details>
  <summary>Gifs</summary>

## ToppDev <--> duckyb/feature/remove-diodes-from-top
Left-ToppDev-duckyb-feature

## ToppDev <--> duckyb/master
Left-ToppDev-duckyb-master

</details>

# Right

<details>
  <summary>Pictures</summary>

Right-ToppDev
Right-duckyb-feature
Right-duckyb-master

</details>

<details>
  <summary>Gifs</summary>

## ToppDev <--> duckyb/feature/remove-diodes-from-top
Right-ToppDev-duckyb-feature

## ToppDev <--> duckyb/master
Right-ToppDev-duckyb-master

</details>

### CODE REVIEW

**Comment by duckyb** [comment]
Updating to Kicad 8 was a bad idea... It's still unsupported by everything. I'll revert to Kicad 7 and undo the commit

**Comment by ToppDev** [comment]
If I can help with something. Please let me know. I am quite interested in getting these changes in, as I want to order a PCB to build my own urchin soon

**Comment by duckyb** [comment]
It should be no problem to build a gerber from your latest commit if you want to speed ahead. I need to downgrade my version of Kicad and replace the last commit, I think I'll be able to do it tomorrow afternoon.

After that I need to update the Kibot job to support Kicad 7 and test the pcb image generation.

The changes I made to your commit were just cosmetic.

**Comment by ToppDev** [comment]
I can wait don't worry. Thank you for your effort

**Pull request merged**
